version: '3.3'

networks:
  poc-bridge:
    external: true


services:
  mqtt-edge:
    image: emqx/emqx-edge:latest
    container_name: edge-broker
    restart: always
    environment:
      - EMQX_LOADED_PLUGINS="emqx_bridge_mqtt,emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
      - EMQX_ADMIN_PASSWORD=brokerpw1                                                                                            
    networks:
      - poc-bridge   
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
  server:
    image: arijitnandi/fedserver
    env_file:
      - /home/ubuntu/Fed-ReMECS-Docker/server-src/config.env
    volumes:
      - /home/ubuntu/fedserver-data/data:/home/data
      - /home/ubuntu/fedserver-data/global_model:/home/global_model
      - /home/ubuntu/fedserver-data/local_model:/home/local_model
    depends_on:
      - mqtt-edge
    links:
      - mqtt-edge
    tty: true
    networks:
      - poc-bridge
