version: "3"

services:

  server:
    image: arijitnandi/fedserver
    ports: 
      - 80:80
    links:
      - mqtt
    depends_on: 
      - mqtt
    env_file:
      - ./config.env
    volumes:
      - /home/ubuntu/fedserver-data/data:/home/data
      - /home/ubuntu/fedserver-data/global_model:/home/global_model
      - /home/ubuntu/fedserver-data/local_model:/home/local_model
  
  mqtt: 
    image: toke/mosquitto
    network_mode: bridge
    expose: 
      - 1883
      - 9001
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/ubuntu/mqtt/data:/mosquitto/data
      - /home/ubuntu/mqtt/log:/mosquitto/log
      - /home/ubuntu/mqtt/config:/mosquitto/config
    restart: unless-stopped
    
