version: "3"

services:

  server:
    image: arijitnandi/fedserver
    ports: 
      - 80:80
    links:
      - mqtt
    depends_on: 
      - mqtt
    env_file:
      - ./config.env
    volumes:
      - /home/ubuntu/fedserver-data/data:/home/data
      - /home/ubuntu/fedserver-data/global_model:/home/global_model
      - /home/ubuntu/fedserver-data/local_model:/home/local_model
  
  mqtt: 
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/ubuntu/mqtt/data:/mosquitto/data
      - /home/ubuntu/mqtt/log:/mosquitto/log
    restart: unless-stopped
    
